# stages:
#   - build

# variables:
#   DOCKER_REGISTRY: ghcr.io  # GitHub Container Registry
#   IMAGE_TAG: $DOCKER_REGISTRY/inknight-dednet/comfy_container_ui/c_c_u:latest

# before_script:
#   - apt-get update && apt-get install -y curl
#   - curl -I https://download.pytorch.org/whl/rocm6.2

# build:
#   stage: build
#   image: docker:latest
#   services:
#     - docker:dind  # 启动 Docker in Docker
#   script:
#     - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY
#     - docker buildx create --use  # 设置 Buildx
#     - docker buildx build --file ./Dockerfile --push --tag $IMAGE_TAG .