kind: pipeline
name: Build and Push Docker Image to Gitea Container Registry

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git clone --depth 1 ${CI_REPO} .

  - name: setup-buildx
    image: docker:23
    privileged: true
    commands:
      - docker buildx create --use

  - name: build-docker-image
    image: docker:23
    commands:
      - docker buildx build --file ./Dockerfile --tag ${CI_REGISTRY}/comfy_container_ui/c_c_u:latest .

  - name: push-docker-image
    image: docker:23
    environment:
      DOCKER_PASSWORD:
        from_secret: package_gitea_token
    commands:
      - echo "${package_gitea_token}" | docker login ${CI_REGISTRY} -u "${CI_COMMITTER}" --password-stdin
      - docker push ${CI_REGISTRY}/comfy_container_ui/c_c_u:latest

trigger:
  event:
    - push
  branch:
    - main