name: Build and Push Docker Image to Nexus3 Container Registry

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --file ./Dockerfile --tag hub.dednet.co/inknight-dednet/comfy_container_ui/c_c_u:latest .

  push:
    runs-on: ubuntu-latest
    needs: build  # 确保推送在构建之后执行

    steps:
      - name: Login to Nexus3 Container Registry
        uses: docker/login-action@v2
        with:
          registry: hub.dednet.co  # Nexus3 容器注册表域名
          username: ${{ secrets.NEXUS_USERNAME }}  # Nexus3 用户名
          password: ${{ secrets.NEXUS_PASSWORD }}  # Nexus3 密码

      - name: Push Docker image to Nexus3 Container Registry
        run: |
          docker push hub.dednet.co/inknight-dednet/comfy_container_ui/c_c_u:latest
