name: Build and Push Docker Image to GitHub Container Registry

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --file ./Dockerfile --tag ghcr.io/inknight-dednet/comfy_container_ui/c_c_u:latest .

  push:
    runs-on: ubuntu-latest
    needs: build  # 确保推送在构建之后执行

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/inknight-dednet/comfy_container_ui/c_c_u:latest
